with open('src/services/api.ts', 'r') as f:
    lines = f.readlines()

new_lines = lines[:263]

new_lines.extend([
    "  static async generateVideoPlan(params: {\n",
    "    name: string;\n",
    "    idea: string;\n",
    "    type: string;\n",
    "    aspectRatio: string;\n",
    "    duration: string;\n",
    "    style: string;\n",
    "    voice: string;\n",
    "    language: string;\n",
    "    music: string;\n",
    "  }): Promise<{ summary: string; fullScript: string; scenes: VideoScene[] }> {\n",
    "    const res = await fetch('/api/ai/video-plan', {\n",
    "      method: 'POST',\n",
    "      headers: { 'Content-Type': 'application/json' },\n",
    "      body: JSON.stringify(params)\n",
    "    });\n",
    "    if (!res.ok) throw new Error('Server request failed. Missing API configuration?');\n",
    "    return await res.json();\n",
    "  }\n",
    "\n",
    "  static async generateShortsPlan(params: {\n",
    "    topic: string;\n",
    "    hook?: string;\n",
    "    script?: string;\n",
    "    visualStyle?: string;\n",
    "    voice?: string;\n",
    "    music?: string;\n",
    "    captionStyle?: string;\n",
    "  }): Promise<ShortsGenerationPlan> {\n",
    "    const res = await fetch('/api/ai/shorts-plan', {\n",
    "      method: 'POST',\n",
    "      headers: { 'Content-Type': 'application/json' },\n",
    "      body: JSON.stringify(params)\n",
    "    });\n",
    "    if (!res.ok) throw new Error('Shorts plan generation failed. Missing API configuration?');\n",
    "    return await res.json();\n",
    "  }\n",
    "\n",
    "  static async generateContentAssistant(params: {\n",
    "    prompt: string;\n",
    "    videoType?: string;\n",
    "    targetAudience?: string;\n",
    "    language?: string;\n",
    "    mainKeyword?: string;\n",
    "  }): Promise<AIContentPack> {\n",
    "    const res = await fetch('/api/ai/content-assistant', {\n",
    "      method: 'POST',\n",
    "      headers: { 'Content-Type': 'application/json' },\n",
    "      body: JSON.stringify(params)\n",
    "    });\n",
    "    if (!res.ok) throw new Error('Content generation failed. Missing API configuration?');\n",
    "    return await res.json();\n",
    "  }\n",
    "\n",
    "  static async generateThumbnailConcept(params: {\n",
    "    idea: string;\n",
    "    title?: string;\n",
    "    style?: string;\n",
    "    aspectRatio?: '16:9' | '9:16';\n",
    "  }): Promise<ThumbnailConcept> {\n",
    "    const res = await fetch('/api/ai/thumbnail-concept', {\n",
    "      method: 'POST',\n",
    "      headers: { 'Content-Type': 'application/json' },\n",
    "      body: JSON.stringify(params)\n",
    "    });\n",
    "    if (!res.ok) throw new Error('Thumbnail concept failed. Missing API configuration?');\n",
    "    return await res.json();\n",
    "  }\n",
    "}\n"
])

with open('src/services/api.ts', 'w') as f:
    f.writelines(new_lines)

