export {
  type AuthUser,
  COOKIE_NAME,
  SESSION_DURATION_DAYS,
  getSessionSecret,
  getSafeHost,
  getSafeProto,
  getBaseUrl,
  getGoogleRedirectUri,
  isGoogleOAuthConfigured,
  getGoogleAuthorizationUrl,
  exchangeGoogleCodeForUser,
  findOrCreateGoogleUser,
  createUserSession,
  setSessionCookie,
  clearSessionCookie,
  extractSessionCredentials,
  validateSession,
  attachUserMiddleware,
  requireAuth,
  revokeSession
} from '../api/index';
